=== CofiTy/XmlParser/Test/rap6.dtd
<!ELEMENT DatabaseInventory (DatabaseName+)>
<!ELEMENT DatabaseName (GlobalDatabaseName,OracleSID,DatabaseDomain,Administrator+,DatabaseAttributes, Comments)>
<!ELEMENT GlobalDatabaseName (#PCDATA)>
<!ELEMENT OracleSID          (#PCDATA)>
<!ELEMENT DatabaseDomain     (#PCDATA)>
<!ELEMENT Administrator      (#PCDATA)>
<!ELEMENT DatabaseAttributes (#PCDATA)>
<!ELEMENT Comments           (#PCDATA)>
<!ATTLIST Administrator       EmailAlias CDATA #IMPLIED>
<!ATTLIST Administrator       Extension  CDATA #IMPLIED>

=== CofiTy/XmlParser/Test/rap6.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE rapport SYSTEM "Test/rap6.dtd">

<DatabaseInventory>
  <DatabaseName>
    <GlobalDatabaseName>Base1</GlobalDatabaseName>
    <OracleSID>prod</OracleSID>
    <DatabaseDomain>Domain</DatabaseDomain>
    <Administrator EmailAlias="Alias" Extension="333">Admin</Administrator>
    <DatabaseAttributes>att</DatabaseAttributes>
    <Comments>Comment</Comments>
  </DatabaseName>
</DatabaseInventory>
